### ISSUE TITLE
Request: Add support for channels

### ISSUE THREAD

**Issue by mfaulkinbury** [NLog/NLog.Etw#14]
As an NLog-consuming program author, I would like to leverage the new features (starting with ETW channel support) available in the [Microsoft EventSource Library](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource) so that I may later register, then use Windows Event Viewer to easily view my application's log entries as well as enable/disable channel-related logs.

**Comment by mfaulkinbury** [comment]
@304NotModified

Hi Julian,
I've added comments to your review entries, but have come to realize that this issue may be trying to address too many items at once.
The main block for us was channel support.  I would be happy to reduce this issue to just that and handle event registration and logs in separate issues (possibly implemented in a separate package) if that would help us move forward.
Thoughts?
Best,
Mike

**Comment by 304NotModified** [comment]
Smaller pull requests are always better indeed :)

Please do, then I will try to look at it in a short time
