### ISSUE TITLE
Latest version 4.1.0 not published to NuGet

### ISSUE THREAD

**Issue by mfaulkinbury** [NLog/NLog.Etw#16]
Please push the newest version of the package.

**Comment by 304NotModified** [comment]
Is was waiting on a response at https://github.com/NLog/NLog.Etw/pull/15

**Comment by mfaulkinbury** [comment]
From me?  I'm still quite a novice.  Would you mind pointing out the question requiring a response (I think I've responded to everything, but may not have done so correctly)?

**Comment by 304NotModified** [comment]
See link ;)

**Comment by 304NotModified** [comment]
Done :)
