### ISSUE TITLE
Request: Support for .net standard

### ISSUE THREAD

**Issue by shake82** [NLog/NLog.Etw#22]
Please add .net standard as one of the build targets

**Comment by snakefoot** [comment]
Already resolved with #18. @304NotModified "just" have to publish an updated nuget-package.

**Comment by shake82** [comment]
Awesome. Thanks for the quick reply

**Comment by 304NotModified** [comment]
working on the deployment

**Comment by snakefoot** [comment]
@shake82 NLog.Etw ver. 4.2 is now ready: https://www.nuget.org/packages/NLog.Etw

**Comment by shake82** [comment]
Thanks!
