### ISSUE TITLE
Any plans for upgrading to NLog.5.0.0?

### ISSUE THREAD

**Issue by wiliammbr** [NLog/NLog.Etw#50]
Just a touch base to check if you have any plans to support NLog 5.

**Comment by snakefoot** [comment]
The existing version should work just fine with NLog 5 (Very few breaking changes in NLog5, so most extensions are unaffected). 

Do you have a different experience?

**Comment by wiliammbr** [comment]
Hey @snakefoot , thanks for reaching out.
Well, we have one project running .NET Framework 4.6. Recently we upgraded NLog to v5, but there are some scenarios where we load NLog.Etw and it fails, specially from PowerShell scripts loading the Assembly directly. It keeps looking for version 4.0.0.0 of NLog, even though we added Binding Redirects to our main project.

**Comment by 304NotModified** [comment]
I think it's a good idea to update this one to NLog 5 indeed

**Comment by 304NotModified** [comment]
@wiliammbr preview package: ~https://_ci.appveyor.com/api/buildjobs/x5vcwqrg827gr0fe/artifacts/artifacts%2FNLog.Etw.5.0.0.nupkg~
https://ci.appveyor.com/api/buildjobs/bv71pcsohof270qd/artifacts/artifacts%2FNLog.Etw.5.0.0.nupkg

Please give your feedback.

**Comment by snakefoot** [comment]
Also think we should update to NLog 5. Was just curious if there was something unexpected that was breaking.

But yes strong-version-assembly-issues with binding redirects are expected between NLog4 and NLog5, when using .NET Framework.

**Comment by 304NotModified** [comment]
5.0.0-rc1 is now on nuget. https://www.nuget.org/packages/NLog.Etw/5.0.0-rc1

Please your feedback :)

**Comment by wiliammbr** [comment]
Hey @304NotModified , with this new version the problem is gone. For me it will be good to be published as the first version.

**Comment by 304NotModified** [comment]
thanks, publishing 5.0 now!

**Comment by 304NotModified** [comment]
It's live: https://www.nuget.org/packages/NLog.Etw/5.0.0

**Comment by wiliammbr** [comment]
Great! Appreciate the help here @304NotModified :)
