### ISSUE TITLE
Bump Microsoft.Diagnostics.Tracing.EventSource.Redist

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Etw#52]
Current Version 1.x, should we move to 2+?

[package link](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource.Redist/#dependencies-body-tab)

**Comment by snakefoot** [comment]
Either remove net45 or leave its dependencies alone.

**Comment by 304NotModified** [comment]
Ow yes you're right.

- Microsoft.Diagnostics.Tracing.EventSource.Redist is only used for net45
- Microsoft.Diagnostics.Tracing.EventSource.Redist 2.0+ don't support net45
